version: "3"

services:
    api:
        build: .
        depends_on:
          - postgres
        ports:
          - 8000:8000
        volumes:
          - ./:/usr/src/app:ro
        environment:
          - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
          - DATABASE_PORT=${DATABASE_PORT}
          - DATABASE_PASSWORD=${DATABASE_PASSWORD}
          - DATABASE_NAME=${DATABASE_NAME}
          - DATABASE_USERNAME=${DATABASE_USERNAME}
          - SECRET_KEY=${SECRET_KEY}
          - ALGORITHM=${ALGORITHM}
          - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload && bash -c alembic upgrade head
    postgres:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=fastapi

      volumes:
        - postgres-db-volume:/var/lib/postgresql/data
volumes:
  postgres-db-volume:
